# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8d4a4a6454090d2b0352a87762f3f30"
name = "test-del-customization"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "test-del-customizations"

[build]

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
